# This is a default, unmodified configuration that will NOT work by default.
server_address=http://192.168.1.238:4533
user=naviplayer
password=Jamieson413.!
server_auth=token
mpv_path=/usr/bin/mpv
replay_gain=auto
primary_accent=yellow
secondary_accent=gray
home_list_size=30
follow_cursor_queue=true
draw_while_unfocused=false
