[font]
size = 11
    normal = { family = "Cozette", style = "Regular" }
    bold = { family = "Cozette", style = "Bold" }
    italic = { family = "Cozette", style = "Italic" }
    bold_italic = { family = "Cozette", style = "Bold Italic" }
